# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12H1ezpmaoc7FxKn_ad6lMCIwnPSmhjug
"""

import pandas as pd

data = {"name" :['alice', 'bob', 'charlie'] ,
        'age': [25,30,35] ,
        'city': ['NY', 'LA', 'China']}

df = pd.DataFrame(data)

df

df1 = pd.read_csv("/content/sample_data/california_housing_test.csv")

import numpy as np

arr= np.array([10,20,30,40,50])

arr

arr.ndim

arr2 = np.array([[1,2,3], [4,5,6]])

arr2.ndim

df1 = pd.read_csv("/content/sample_data/california_housing_test.csv")

"""#data inspection"""

df1.head()   #.head is for 1st 5 rows

df1.head(3)

df1.tail()

df1.tail(3)

df1.shape

df1.size

df1.ndim

df1.info()

df1.describe()

df1.columns

df1.index

#this dataframe contain all float data types with 64 bit
#the range of data is between 0 to 3000. total data is 27000 of entries
df1.dtypes

df1.memory_usage()

df1.sample(5)

"""#slicing"""

df3 = df1['latitude']

df3

df3.mean()

df1[['latitude', 'longitude']]

df1.columns

df1.loc[2998]   #location but using index name

df1.iloc[2998]  #index location

df1.loc[2 :5]

list = [45,87,9,5]

list[3]

"""#data cleaning"""

df1.isnull()

df1.isnull().sum()

df1.notnull()

df1.notnull().sum()

df1.dropna()

data = {
    'age': [25, 30, np.nan, 45, 50, np.nan, 60, 35, np.nan, 40]
}

df = pd.DataFrame(data)

df

df.isnull()

df.isnull().sum()

df_dropped = df.dropna()

df_dropped

df

df_filled = df.fillna(0)

df_filled

df_filled_mean = df.fillna(df['age'].mean())

df_filled_mean

df_filled_mean.duplicated()

df_filled_mean.duplicated().sum()

