# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUMBcXLuIqTOgcA6pGJav-buvtsfi6q0

#For - loop

is is use for comperhentioin (short code )
"""

fruits = ["apple", "banana", "kiwi", "orange"]

fruits[1]  #1 is index of banana

fruits[0:2]

index = 0
while index <= len(fruits):
  print(fruits[index])
  index +=1

fruits

for fru in fruits:      #in is a keywords
  print(fru)

for i in range(5):
  print (i)

#using while

name = "Harsh"

index =0

while index < len(name):
  print(name[index])
  index +=1

name

for char in name:
  print(char)

number = [1,2,3,4,5,6]

for num in number:
  if num % 2 == 0:
    print(num, "number is even")
  else:
    print(num, "number is odd")

#prime number from from 1 and 100

number = 5

int ( number ** 0.5 ) +1

for num in range(1 , 101):
  if num >1:
    for i in range(2 , int(num ** 0.5)+1):

      if num % i == 0:
        break          #break statement use to break
      else:
        print(num, end =" \n ")       #\n is use for next line

#counting vowels in a string using while loop

string = input("Enter a string: ")
vowels = "aeiouAEIOU"
i = 0
index = 0

while index < len(string):
    if string[index] in vowels:
        i += 1
    index += 1

print("Number of vowels:", i)

# PATTERN PRINT

n = 5
for i in range(1, n + 1):
    print(' ' * (n - i) + '*' * (2 * i - 1))

#sum of even number using for loop range 1 to 100

sum_of_even = 0

for num in range(1, 101):
  if num % 2 == 0 :
    sum_of_even = sum_of_even + num

print("sum of even number from 1 to 100 is :-", sum_of_even)

"""#Functions

A function is a reusable block of code that perform specific task.

A function helps in breaking the program into smaller manageable parts

Function Syntax

#syntax

def function_name(parameters):

    block of code
    
    return result
"""

def greeting_card():
  print ("Hello, Happy Diwali, My name is Harsh")

greeting_card()

#with parameter

def greet(name):
  print("Hello, Happy Diwali From", name)

greet("Harsh")

greet("Dipali")

#return statement

def addition(a,b):
  return a + b

addition(5,6)

def addition(a,b,c,d):
  return a + b +c +d

addition(1,2,3,4)

# default parameter

"""#default arguments"""

def pincode(pin = 442001):
  print("pincode is", pin)

pincode()

pincode(442233)

def calculate_Area(width, height =1):
  return width * height

area1= calculate_Area(5 , 10)
area2 = calculate_Area(5)


print("area1 is:-", area1)
print("area2 is:-", area2)

"""#Lambda function"""

num = int(input("Enter your number : - "))

def square(num):
  return num ** 2

square(num)

num= int(input("Enter your number :- "))
square_new = lambda num: num **2

print(square_new(num))

add = lambda a, b: a + b

print(add(10,20))

#concatination ( add two strings)

concat = lambda str1, str2 :str1 + " " +str2

print(concat("Harsh", "Thakare"))

max_value = lambda x, y :x if x >y else y

print("The maximun number is ", max_value(15 , 17))

