# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaM6wHG6XtR_iTy8wLR8LcrdVyX4705R

#seaborn
"""

import seaborn as sns

import matplotlib.pyplot as plt

# . set_style  - eg - whitegrid, darkgrid, white, dark , ticks

sns.set_style('darkgrid')
sns.lineplot(x=[1,2,3], y=[1,4,9])
plt.show()

sns.set_style('dark')
sns.lineplot(x=[1,2,3], y=[1,4,9])
plt.show()

sns.set_style('ticks')
sns.lineplot(x=[1,2,3], y=[1,4,9])
plt.show()

# set_context ()  -eg- paper, notebook, talk, poster

x =[ 1,2,3]
y = [1,4,9]
sns.set_context("talk")
sns.lineplot(x=[1, 2, 3], y=[1, 4, 9])
plt.show()

sns.set_context("poster")
sns.lineplot(x=[1, 2, 3], y=[1, 4, 9])
plt.show()

"""#plotting

scatterplot
"""

sns.scatterplot(x =[ 1,2,3], y=[4,5,6])

sns.scatterplot(x=[1,2,3,4], y =[4,5,6,7], hue =[0,1,1,0])
plt.show()

sns.barplot(x=['A', 'B', 'C'], y = [10, 15, 7])

sns.histplot([1,2,2,3,3,3,4,4,5])

sns.histplot([1,2,2,3,3,3,4,4,5], kde =True)

sns.boxplot(y = [7,8,6,5,9,10])
plt.show()

sns.violinplot(y =[7,8,6,5,9,10,500])

irish = sns.load_dataset('iris')

irish.head()

import seaborn as sns
iris = sns.load_dataset('iris')
sns.pairplot(iris)
plt.show()

sns.pairplot(irish, hue ='species')

import numpy as np

data = np.array([[1,2,3], [4,5,6], [7,8,9]])

sns.heatmap(data, annot=True)
plt.show()

sns.heatmap(data, annot=True, cmap='YlGnBu')

"""#sns. for distributions plot"""

sns.kdeplot([1,2,3,4,5,6])
plt.show()

irish.head()

sns.kdeplot(irish['sepal_length'])

titanic = sns.load_dataset('titanic')

titanic.head()

sns.kdeplot(titanic['age'])

sns.boxplot(titanic['age'])

sns.displot(titanic['age'])

sns.displot(titanic['age'], kde =True)

irish.head()

sns.relplot(x='sepal_length', y='sepal_width',data =irish)

sns.relplot(x='sepal_length', y='sepal_width',data =irish, kind='line')

sns.catplot(x='species', y='sepal_length', kind='bar', data =irish)

sns.catplot(x='species', y='sepal_length', kind='box', data =irish)

x=['A', 'B', 'C']
y = [10, 15, 7]
sns.barplot(x =x, y = y )

